#
# Version  1.0
#


# pull base image
FROM ubuntu:20.04

RUN apt-get update  && \
    echo "===> Installing Ansible..."  && \
    apt-get install -y ansible  && \
    echo "===> Adding hosts for convenience..."  && \
    echo 'localhost' > /etc/ansible/hosts


COPY ansible-playbook-wrapper /usr/local/bin/

RUN  DEBIAN_FRONTEND=noninteractive  apt-get update   && \
              echo "===> Updating TLS certificates..."         && \
              apt-get install -y openssl ca-certificates

WORKDIR  /tmp
COPY  .  /tmp
RUN  \
              echo "===> Diagnosis: host information..."  && \
              ansible -c local -m setup all

#
# build phase
#

ENV PLAYBOOK test.yml
RUN echo "===> Installing git for ansible galaxy..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f git
RUN ansible-playbook-wrapper -e 'prometheus_use_systemd=false'


#
# test phase
#

RUN echo "==> Removing PID files..."  && \
    rm -f /var/run/prometheus/*

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl


VOLUME ["/data"]
ENV    RESULT     /data/result-ubuntu20.04

CMD  \
     service node_exporter start  &&  sleep 10  &&  \
     service alertmanager start   &&  sleep 10  &&  \
     service prometheus start     &&  sleep 60  &&  \
     curl --retry 5 --retry-max-time 120  http://localhost:9100/metrics  > $RESULT   && \
     curl --retry 5 --retry-max-time 120  http://localhost:9093/metrics  >> $RESULT  && \
     curl --retry 5 --retry-max-time 120  http://localhost:9090/metrics  >> $RESULT
