#
# Version  1.0
#


# pull base image
FROM debian:buster


#
# build phase
#

RUN echo "===> Adding Ansible's prerequisites..."         && \
    apt-get update -y  &&  apt-get install --fix-missing  && \
    echo "===> Installing Ansible..."  && \
    apt-get install -y ansible git sudo curl build-essential \
    python python-yaml gcc python-pip python-dev libffi-dev libssl-dev && \
    echo "===> Adding hosts for convenience..."  && \
    mkdir -p /etc/ansible                        && \
    echo 'localhost' > /etc/ansible/hosts

COPY ansible-playbook-wrapper /usr/local/bin/

RUN  DEBIAN_FRONTEND=noninteractive  apt-get update   && \
              echo "===> Updating TLS certificates..."         && \
              apt-get install -y openssl ca-certificates

WORKDIR  /tmp
COPY  .  /tmp
RUN  \
              echo "===> Diagnosis: host information..."  && \
              ansible -c local -m setup all

ENV PLAYBOOK test.yml
RUN ansible-playbook-wrapper -e 'prometheus_use_systemd=false'


ENV PATH        /opt/ansible/bin:$PATH
ENV PYTHONPATH  /opt/ansible/lib:$PYTHONPATH
ENV MANPATH     /opt/ansible/docs/man:$MANPATH


#
# test phase
#

RUN echo "==> Removing PID files..."  && \
    rm -f /var/run/prometheus/*

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl


VOLUME ["/data"]
ENV    RESULT     /data/result-debian10

CMD  \
     service node_exporter start  &&  sleep 10  &&  \
     service alertmanager start   &&  sleep 10  &&  \
     service prometheus start     &&  sleep 60  &&  \
     curl --retry 5 --retry-max-time 120  http://localhost:9100/metrics  > $RESULT   && \
     curl --retry 5 --retry-max-time 120  http://localhost:9093/metrics  >> $RESULT  && \
     curl --retry 5 --retry-max-time 120  http://localhost:9090/metrics  >> $RESULT
