- hosts: all
  become: True
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'

  vars:

    #prometheus_components: [ "prometheus" ]
    #prometheus_components: [ "node_exporter" ]
    #prometheus_components: [ "alertmanager" ]
    prometheus_components: [ "prometheus", "node_exporter", "alertmanager" ]
    #prometheus_alertmanager_version: git


    #prometheus_rule_files:
    #  this_is_rule_1_InstanceDown:
    #    src:  test/basic.rules
    #    dest: basic.rules


    prometheus_alertmanager_url: "http://localhost:9093/"

    #prometheus_alertmanager_conf: test/alertmanager.yml.j2

  post_tasks:
    - name: copy file_sd
      copy: src="{{ playbook_dir }}/test/file_sd.yml"  dest={{ prometheus_file_sd_config_path }}
